# Generated by Django 4.1.4 on 2023-02-07 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(default='unknown@gmail.com', max_length=254)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('phnum', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='approve_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_code', models.CharField(blank=True, max_length=10, null=True)),
                ('reason', models.CharField(blank=True, max_length=10, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('admin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(default='unknown@gmail.com', max_length=254)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('phnum', models.IntegerField(blank=True, null=True)),
                ('skill', models.CharField(blank=True, max_length=100, null=True)),
                ('roll', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='get_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('usercode', models.CharField(blank=True, max_length=10, null=True)),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('project_progress', models.CharField(blank=True, max_length=100, null=True)),
                ('project_date', models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 2, 7, 6, 48, 42, 118832, tzinfo=datetime.timezone.utc))),
                ('end_date', models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 2, 7, 6, 48, 42, 118832, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='hr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('hr_code', models.CharField(blank=True, max_length=10, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(default='unknown@gmail.com', max_length=254)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('phnum', models.IntegerField(blank=True, null=True)),
                ('roll', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_code', models.CharField(blank=True, max_length=10, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(default='unknown@gmail.com', max_length=254)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('phnum', models.IntegerField(blank=True, null=True)),
                ('roll', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='request_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_code', models.CharField(blank=True, max_length=10, null=True)),
                ('reason', models.CharField(blank=True, max_length=10, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='send_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('usercode', models.CharField(blank=True, max_length=10, null=True)),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('project_progress', models.CharField(blank=True, max_length=100, null=True)),
                ('project_date', models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 2, 7, 6, 48, 42, 118832, tzinfo=datetime.timezone.utc))),
                ('end_date', models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 2, 7, 6, 48, 42, 118832, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
