# Generated by Django 4.1.4 on 2023-02-07 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_report',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 2, 7, 6, 49, 17, 341276, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='get_report',
            name='project_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 2, 7, 6, 49, 17, 341276, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='send_report',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 2, 7, 6, 49, 17, 341276, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='send_report',
            name='project_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 2, 7, 6, 49, 17, 340270, tzinfo=datetime.timezone.utc)),
        ),
    ]
