# Generated by Django 4.1.4 on 2023-02-07 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_get_report_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_report',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 2, 7, 6, 54, 3, 210014, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='get_report',
            name='project_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 2, 7, 6, 54, 3, 210014, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='send_report',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 2, 7, 6, 54, 3, 210014, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='send_report',
            name='project_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 2, 7, 6, 54, 3, 210014, tzinfo=datetime.timezone.utc)),
        ),
    ]
