# Generated by Django 4.1.4 on 2023-02-07 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_get_report_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve_leave',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='get_report',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 2, 7, 7, 25, 15, 836818, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='get_report',
            name='project_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 2, 7, 7, 25, 15, 836818, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request_leave',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='send_report',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 2, 7, 7, 25, 15, 836818, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='send_report',
            name='project_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 2, 7, 7, 25, 15, 836818, tzinfo=datetime.timezone.utc)),
        ),
    ]
